<a href="https://colab.research.google.com/github/Aasthapaudel/datathon/blob/main/Asap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn 
import os
import glob

In [143]:
path=os.getcwd()
csv_files =glob.iglob(os.path.join(path, "*csv"))
for d in csv_files:
  df=pd.read_csv(d)
  display(df)

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2659,4,चन्द्र बहादुर बुढा,पुरुष,49,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),बागलुङ,2,1,17415,Elected,1
1,2660,4,मञ्जेश बम मल्ल,पुरुष,40,नेपाली काँग्रेस,बागलुङ,2,1,11546,NaN,2
2,2661,4,विर बहादुर दर्जी,पुरुष,35,संघीय समाजवादी फोरम नेपाल,बागलुङ,2,1,255,NaN,3
3,2660,4,मञ्जेश बम मल्ल,पुरुष,40,नेपाली काँग्रेस,बागलुङ,2,1,11546,NaN,2
4,2661,4,विर बहादुर दर्जी,पुरुष,35,संघीय समाजवादी फोरम नेपाल,बागलुङ,2,1,255,NaN,3
5,2660,4,मञ्जेश बम मल्ल,पुरुष,40,नेपाली काँग्रेस,बागलुङ,2,1,11546,NaN,2
6,2661,4,विर बहादुर दर्जी,पुरुष,35,संघीय समाजवादी फोरम नेपाल,बागलुङ,2,1,255,NaN,3

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2673,4,विकास लंसाल,पुरुष,48,नेपाल कम्युनिष्ट पार्टी (एमाले),पर्वत,1,2,15434,Elected,1
1,2674,4,राजेन्द्र प्रसाद तिवारी,पुरुष,41,नेपाली काँग्रेस,पर्वत,1,2,13352,NaN,2
2,2675,4,ड‍ोलनाथ भुसाल,पुरुष,40,राष्ट्रिय जनमोर्चा,पर्वत,1,2,274,NaN,3
3,2676,4,लिलाधर आचार्य,पुरुष,45,नेपाल कम्युनिष्ट पार्टी (माले),पर्वत,1,2,252,NaN,4
4,2677,4,टोकेन्द्र राना,पुरुष,42,राष्ट्रिय जनमुक्ति पार्टी,पर्वत,1,2,162,NaN,5
5,2678,4,ओम बहादुर भण्डारी,पुरुष,41,नयाँ शक्ति पार्टी नेपाल,पर्वत,1,2,55,NaN,6
6,2679,4,जित बहादुर सार्की,पुरुष,57,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,पर्वत,1,2,51,NaN,7
7,2680,4,यज्ञ प्रसाद तिवारी,पुरुष,49,स्वतन्त्र,पर्वत,1,2,4,NaN,8

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1606,4,देवेन्द्र पौडेल,पुरुष,52,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),बागलुङ,2,28827,Elected,1
1,1607,4,नर बहादुर पुन,NaN,58,नेपाली काँग्रेस,बागलुङ,2,19905,NaN,2
2,1608,4,निल बहादुर पुन,पुरुष,64,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,बागलुङ,2,586,NaN,3
3,1609,4,बाबुराम पाण्डे,पुरुष,41,आमूल परिवर्तन मसिहा पार्टी नेपाल,बागलुङ,2,262,NaN,4
4,1610,4,याम बहादुर घर्तीमगर,पुरुष,40,संघीय समाजवादी फोरम नेपाल,बागलुङ,2,180,NaN,5

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2329,4,रोशन बहादुर गाहा थापा,पुरुष,54,नेपाल कम्युनिष्ट पार्टी (एमाले),नवलपरासी (बर्दघाट सुस्ता पूर्व),1,2,20790,Elected,1
1,2330,4,महेन्द्र ध्वज जि.सि.,पुरुष,59,नेपाली काँग्रेस,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,2,19941,NaN,2
2,2331,4,पदमाया गाहा मगर,महिला,25,राष्ट्रिय जनमुक्ति पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,2,353,NaN,3
3,2332,4,रुद्र बहादुर गुरुङ्ग,पुरुष,58,नयाँ शक्ति पार्टी नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,2,332,NaN,4
4,2333,4,राम प्रसाद चापागाई,पुरुष,35,विवेकशील साझा पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,2,287,NaN,5
5,2334,4,राम बहादुर श्रेष्ठ,पुरुष,59,राष्ट्रिय प्रजातन्त्र पार्टी (प्रजातान्त्रिक),नवलपरासी (बर्दघाट सुस्ता पूर्व),1,2,192,NaN,6
6,2335,4,विष्‍णु प्रसाद खत्री केसी,पुरुष,30,राष्ट्रिय प्रजातन्त्र पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,2,69,NaN,7
7,2336,4,मणी प्रसाद न्यौपाने,पुरुष,60,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,2,61,NaN,8
8,2337,4,टम बहादुर थापा मगर,पुरुष,51,मंगोल नेशनल अर्गनाइजेसन,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,2,55,NaN,9
9,2338,4,लालु खराल,पुरुष,51,राष्ट्रिय जनमोर्चा,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,2,39,NaN,10

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1600,4,सुर्य प्रसाद पाठक,पुरुष,41,नेपाल कम्युनिष्ट पार्टी (एमाले),बागलुङ,1,33657.0,Elected,1
1,1601,4,चम्पा देवी खड्का,महिला,53,नेपाली काँग्रेस,बागलुङ,1,20616.0,NaN,2
2,1602,4,कृष्ण प्रसाद शर्मा,पुरुष,46,नयाँ शक्ति पार्टी नेपाल,बागलुङ,1,256.0,NaN,3
3,1603,4,निर बहादुर क्षेत्री,पुरुष,45,नेपाल कम्युनिष्ट पार्टी (माले),बागलुङ,1,NaN,NaN,4
4,1604,4,महेन्‍द्र जी सी,पुरुष,30,संघीय समाजवादी फोरम नेपाल,बागलुङ,1,115.0,NaN,5
5,1605,4,सुमन जंग राजभण्डारी,पुरुष,49,एकीकृत राष्ट्रिय प्रजातन्त्र पार्टी(राष्ट्रवादी),बागलुङ,1,80.0,NaN,6

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2651,4,इन्द्र लाल सापकोटा,पुरुष,47,नेपाल कम्युनिष्ट पार्टी (एमाले),बागलुङ,1,1,17915,Elected,1
1,2652,4,दिपेन्द्र बहादुर थापा,पुरुष,51,नेपाली काँग्रेस,बागलुङ,1,1,11989,NaN,2
2,2653,4,कृष्ण शर्मा,पुरुष,31,नयाँ शक्ति पार्टी नेपाल,बागलुङ,1,1,149,NaN,3
3,2654,4,जय लाल सापकोटा,पुरुष,48,एकीकृत राष्ट्रिय प्रजातन्त्र पार्टी(राष्ट्रवादी),बागलुङ,1,1,98,NaN,4
4,2655,4,बद्री कुमार श्रेष्‍ठ,पुरुष,63,संघीय समाजवादी फोरम नेपाल,बागलुङ,1,1,89,NaN,5

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1300,4,देव प्रसाद गुरुङ,पुरुष,59,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),लमजुंग,1,39468,Elected,1
1,1301,4,दिल बहादुर घर्ती,पुरुष,65,नेपाली काँग्रेस,लमजुंग,1,31067,NaN,2
2,1302,4,निराजन कुवँर,पुरुष,30,जनसमाजवादी पार्टी नेपाल,लमजुंग,1,1406,NaN,3
3,1303,4,द्धारीका प्रसाद मिश्र,पुरुष,50,स्वतन्त्र,लमजुंग,1,732,NaN,4
4,1304,4,निर्देश सिलवाल,पुरुष,27,विवेकशील साझा पार्टी,लमजुंग,1,618,NaN,5
5,1305,4,देवेन्द्र पराजुली,पुरुष,4700,नयाँ शक्ति पार्टी नेपाल,लमजुंग,1,602,NaN,6
6,1306,4,खेमजङ्ग गुरुङ,पुरुष,59,संघीय समाजवादी फोरम नेपाल,लमजुंग,1,399,NaN,7
7,1307,4,यम बहादुर थापा मगर,पुरुष,51,राष्ट्रिय जनमुक्ति पार्टी,लमजुंग,1,103,NaN,8
8,1308,4,मेत्तर गुरुङ,पुरुष,50,देशभक्त समाज,लमजुंग,1,92,NaN,9
9,1309,4,सोम बहादुर गुरुङ,पुरुष,25,मंगोल नेशनल अर्गनाइजेसन,लमजुंग,1,64,NaN,10
10,1310,4,सुरेश चन्द्र न्यौपाने,पुरुष,34,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,लमजुंग,1,29,NaN,11

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1438,4.0,तिल बहादुर महत क्षेत्री,पुरुष,53.0,नेपाल कम्युनिष्ट पार्टी (एमाले),नवलपरासी (बर्दघाट सुस्ता पूर्व),2,39053,Elected,1
1,1439,4.0,विष्णु कुमार कार्की,पुरुष,54.0,नेपाली काँग्रेस,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,37720,NaN,2
2,1440,4.0,सिंह बहादुर थापा,पुरुष,58.0,राष्ट्रिय जनमुक्ति पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,543,NaN,3
3,1441,NaN,ओम नारायण थनेत,पुरुष,41.0,राष्ट्रिय जनता पार्टी नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,296,NaN,4
4,1442,4.0,पिताम्वर महतो,पुरुष,31.0,नयाँ शक्ति पार्टी नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,278,NaN,5
5,1443,4.0,भागिरथ शर्मा,पुरुष,66.0,राष्ट्रिय जनमोर्चा,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,207,NaN,6
6,1442,4.0,बिमु खनाल,पुरुष,66.0,राष्ट्रिय जनमोर्चा,बहिर,2,207,NaN,6
7,1444,4.0,फुल कुमारी पुर्जा पुन,महिला,66.0,संघीय समाजवादी फोरम नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,79,NaN,7
8,1445,4.0,नारायण प्रसाद पंगेनी,पुरुष,38.0,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,69,NaN,8
9,1446,4.0,श्रीकान्त खरेल,पुरुष,37.0,स्वतन्त्र,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,32,NaN,9
10,1447,NaN,चिरञ्जिवी जि.सी.,पुरुष,41.0,स्वतन्त्र,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,26,NaN,10
11,1448,4.0,लक्ष्मी नारायण महतो,पुरुष,NaN,स्वतन्त्र,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,25,NaN,11
12,1449,4.0,बिन्दु काफ्ले,पुरुष,47.0,स्वतन्त्र,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,20,NaN,12

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1611,4,पदम गिरी,पुरुष,40.0,नेपाल कम्युनिष्ट पार्टी (एमाले),पर्वत,1,39275,Elected,1
1,1612,4,अर्जुन प्रसाद जोशी,पुरुष,61.0,नेपाली काँग्रेस,पर्वत,1,26819,NaN,2
2,1613,4,हरी हर थापा,पुरुष,47.0,नेपाल कम्युनिष्ट पार्टी (माले),पर्वत,1,599,NaN,3
3,1614,4,मन कुमारी पुन मगर,महिला,66.0,राष्ट्रिय जनमुक्ति पार्टी,पर्वत,1,255,NaN,4
4,1615,4,गोविन्द प्रसाद पौडेल,पुरुष,53.0,राष्ट्रिय जनमोर्चा,पर्वत,1,234,NaN,5
5,1616,4,कुश्माखर भुसाल,पुरुष,38.0,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,पर्वत,1,88,NaN,6
6,1617,4,लाल कुमारी थापा राना,महिला,31.0,मंगोल नेशनल अर्गनाइजेसन,पर्वत,1,82,NaN,7
7,1618,4,यम बहादुर चोचाङ्गी पुन,पुरुष,37.0,नयाँ शक्ति पार्टी नेपाल,पर्वत,1,81,NaN,8
8,1619,4,जीत बहादुर गुरुङ्ग,पुरुष,48.0,संघीय समाजवादी फोरम नेपाल,पर्वत,1,59,NaN,9
9,1620,4,तिल प्रसाद शर्मा पौडेल,पुरुष,NaN,एकीकृत राष्ट्रिय प्रजातन्त्र पार्टी(राष्ट्रवादी),पर्वत,1,36,NaN,10
10,1621,4,राजेन्द्र नेपाली,पुरुष,46.0,गान्धीवादी पार्टी नेपाल,पर्वत,1,36,NaN,11
11,1622,4,विनोद कुँवर,पुरुष,26.0,स्वतन्त्र,पर्वत,1,7,NaN,12
12,1623,4,इन्दु देवी शर्मा,महिला,39.0,स्वतन्त्र,पर्वत,1,6,NaN,13
13,1624,4,तर्क बहादुर सुनार,पुरुष,39.0,स्वतन्त्र,पर्वत,1,5,NaN,14

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,NaN,4,चिन्त वहादुर घले,पुरुष,61,नेपाली काँग्रेस,मनाङ्ग,1,1,998,Elected,1
1,2109.0,4,दोर्जे डंडुल गुरुङ,पुरुष,63,नेपाल कम्युनिष्ट पार्टी (एमाले),मनाङ्ग,1,1,896,NaN,2

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2112,4,धनञ्जय दवाडी,पुरुष,49,नेपाल कम्युनिष्ट पार्टी (एमाले),लमजुंग,1.0,1,20265,Elected,1.0
1,2113,4,गर्ज बहादुर गुरुङ,पुरुष,55,नेपाली काँग्रेस,लमजुंग,NaN,1,13853,NaN,2.0
2,2114,4,राजु थापा,पुरुष,37,नयाँ शक्ति पार्टी नेपाल,लमजुंग,1.0,1,499,NaN,3.0
3,2115,4,बुद्धि मान परियार,पुरुष,64,जनसमाजवादी पार्टी नेपाल,लमजुंग,1.0,1,461,NaN,4.0
4,2116,4,इन्द्र वहादुर गुरुङ,पुरुष,74,संघीय समाजवादी फोरम नेपाल,लमजुंग,1.0,1,170,NaN,5.0
5,2117,4,तुल्सि राम गुरुङ,पुरुष,25,विवेकशील साझा पार्टी,लमजुंग,1.0,1,149,NaN,NaN

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1374,4.0,पद्‍मा कुमारी अर्याल,महिला,48,नेपाल कम्युनिष्ट पार्टी (एमाले),स्याङ्जा,2,35142,Elected,1
1,1375,4.0,गोपाल मान श्रेष्ठ,पुरुष,70,नेपाली काँग्रेस,स्याङ्जा,2,31436,NaN,2
2,1376,4.0,ईश्‍वर वहादुर राना,पुरुष,44,राष्ट्रिय जनमुक्ति पार्टी,स्याङ्जा,2,483,NaN,3
3,1377,NaN,राजेन्द्र प्रसाद गैह्रे,पुरुष,62,राष्ट्रिय जनमोर्चा,स्याङ्जा,2,180,NaN,4
4,1378,4.0,रत्न बहादुर गुरुङ,पुरुष,56,मंगोल नेशनल अर्गनाइजेसन,स्याङ्जा,2,143,NaN,5
5,1379,4.0,अर्जुन राना,पुरुष,38,संघीय समाजवादी फोरम नेपाल,स्याङ्जा,2,133,NaN,6
6,1380,4.0,टीका राम रेग्मी,पुरुष,44,नयाँ शक्ति पार्टी नेपाल,स्याङ्जा,2,129,NaN,7
7,1381,4.0,राम भक्त भट्टराई,पुरुष,44,नेपाली कांग्रेस (बी.पी.),स्याङ्जा,2,9,NaN,8

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1346,4,कृष्ण कुमार श्रेष्ठ,पुरुष,49,नेपाल कम्युनिष्ट पार्टी (एमाले),तनहुँ,1,34492.0,Elected,1
1,1347,4,रामचन्द्र पौडेल,पुरुष,73,नेपाली काँग्रेस,तनहुँ,1,27690.0,NaN,2
2,1348,4,मान बहादुर थापा,पुरुष,51,नेपाल कम्युनिष्ट पार्टी (माले),तनहुँ,1,1231.0,NaN,3
3,1349,4,हस्त बहादुर किचिम थापा,पुरुष,800,राष्ट्रिय जनमुक्ति पार्टी,तनहुँ,1,457.0,NaN,4
4,1350,4,चेत मणि पाण्डेय,पुरुष,59,एकीकृत राष्ट्रिय प्रजातन्त्र पार्टी(राष्ट्रवादी),तनहुँ,1,198.0,NaN,5
5,1351,4,श्री कुमार श्रेष्ठ,पुरुष,44,राष्ट्रिय जनमोर्चा,तनहुँ,1,67.0,NaN,6
6,1352,4,सुन्दर लाल श्रेष्ठ,पुरुष,54,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,तनहुँ,1,NaN,NaN,7
7,1353,4,दुर्गा बहादुर थापा,पुरुष,37,स्वतन्त्र,तनहुँ,1,52.0,NaN,8
8,1354,4,बुद्धी बहादुर जि.सी.,पुरुष,68,नेपाल कम्युनिष्ट पार्टी (माक्र्सवादी),तनहुँ,1,40.0,NaN,9
9,1355,4,मिन बहादुर गुरुङ,पुरुष,27,मंगोल नेशनल अर्गनाइजेसन,तनहुँ,1,34.0,NaN,10
10,1356,4,रेशम कुमार श्रेष्ठ,पुरुष,45,स्वतन्त्र,तनहुँ,1,17.0,NaN,11

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1322.0,4,रविन्द्र प्रसाद अधिकारी,पुरुष,49,नेपाल कम्युनिष्ट पार्टी (एमाले),कास्की,2,27207.0,Elected,1
1,1323.0,4,देव राज चालिसे,पुरुष,57,नेपाली काँग्रेस,कास्की,2,18661.0,NaN,2
2,1324.0,4,श्रीकृष्‍ण श्रेष्ठ,पुरुष,38,विवेकशील साझा पार्टी,कास्की,2,843.0,NaN,3
3,NaN,4,टेकनाथ भण्डारी,पुरुष,43,नेपाल कम्युनिष्ट पार्टी (माले),कास्की,2,539.0,NaN,4
4,1326.0,4,रत्‍न भट्टचन,महिला,63,संघीय समाजवादी फोरम नेपाल,कास्की,2,340.0,NaN,5
5,1327.0,4,दिपक भण्डारी,पुरुष,40,नयाँ शक्ति पार्टी नेपाल,कास्की,2,283.0,NaN,6
6,1328.0,4,ज्ञान राज गुरुङ्ग,पुरुष,48,मंगोल नेशनल अर्गनाइजेसन,कास्की,2,130.0,NaN,7
7,1329.0,4,निर्मल खत्री,पुरुष,46,स्वतन्त्र,कास्की,2,NaN,NaN,8
8,1330.0,4,दाल कुमारी खत्री,महिला,48,राष्ट्रिय जनमोर्चा,कास्की,2,108.0,NaN,9
9,1331.0,4,कर्ण बहादुर पुन,पुरुष,57,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,कास्की,2,82.0,NaN,10
10,1332.0,4,लक्ष्मी बिश्वकर्मा,महिला,51,नेपाल दलित पार्टी,कास्की,2,65.0,NaN,11
11,1333.0,4,उमा दर्लामी,महिला,36,राष्ट्रिय जनमुक्ति पार्टी,कास्की,2,51.0,NaN,12
12,1334.0,4,बाल कुमार राई,पुरुष,25,संघीय लोकतान्त्रिक राष्ट्रिय मञ्च,कास्की,2,21.0,NaN,13

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2224,4,मिन प्रसाद गुरुङ्ग,पुरुष,54.0,नेपाल कम्युनिष्ट पार्टी (एमाले),NaN,1,2,20248,Elected,1
1,2225,4,तुलसी गिरी,पुरुष,63.0,नेपाली काँग्रेस,स्याङ्जा,1,2,14510,NaN,2
2,2226,4,दिनेश पौडेल,पुरुष,31.0,नयाँ शक्ति पार्टी नेपाल,स्याङ्जा,1,2,375,NaN,3
3,2227,4,विश्ववन्धु पौडेल,पुरुष,59.0,राष्ट्रिय प्रजातन्त्र पार्टी,स्याङ्जा,1,2,339,NaN,4
4,2228,4,नेत्र बहादुर थापा,पुरुष,NaN,नेपाल कम्युनिष्ट पार्टी (माले),स्याङ्जा,1,2,331,NaN,5
5,2229,4,खड्क बहादुर राना,पुरुष,28.0,मंगोल नेशनल अर्गनाइजेसन,स्याङ्जा,1,2,35,NaN,6

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2667,4,नेत्रनाथ अधिकारी,पुरुष,52,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),पर्वत,1,1,21508,Elected,1
1,2668,4,नवराज गुरुङ्ग,पुरुष,61,नेपाली काँग्रेस,पर्वत,1,1,16685,NaN,2
2,2669,4,टिकाराम पुन मगर,पुरुष,29,राष्ट्रिय जनमुक्ति पार्टी,पर्वत,1,1,166,NaN,3
3,2670,4,महेन्द्र जंग लामीछाने,पुरुष,49,नयाँ शक्ति पार्टी नेपाल,पर्वत,1,1,148,NaN,4
4,2671,4,राजेन्द्र प्रसाद शर्मा,पुरुष,45,राष्ट्रिय जनमोर्चा,पर्वत,1,1,119,NaN,5
5,2672,4,महान बहादुर गुरुङग,पुरुष,63,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,पर्वत,1,1,101,NaN,6

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1289,4,डा. बाबुराम भट्टराई,पुरुष,63,नयाँ शक्ति पार्टी नेपाल,गोरखा,2,31807.0,Elected,1
1,1290,4,नारायण काजी श्रेष्‍ठ,पुरुष,58,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),गोरखा,2,24933.0,NaN,2
2,1291,4,देव प्रसाद प्रधान,पुरुष,150,आमूल परिवर्तन मसिहा पार्टी नेपाल,गोरखा,2,180.0,NaN,3
3,1292,4,नवराज थापा,पुरुष,36,विवेकशील साझा पार्टी,गोरखा,2,139.0,NaN,4
4,1293,4,नारायण बहादुर अर्याल,पुरुष,58,राष्ट्रिय जनमुक्ति पार्टी,गोरखा,2,121.0,NaN,5
5,1294,4,सोम बहादुर गरुङ,पुरुष,35,मंगोल नेशनल अर्गनाइजेसन,गोरखा,2,115.0,NaN,6
6,1295,4,नारायण अधिकारी,पुरुष,39,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,गोरखा,2,89.0,NaN,7
7,1296,4,राम कृष्ण ढकाल,पुरुष,29,नेपाल संघीय समाजवादी पार्टी,गोरखा,2,NaN,NaN,8
8,1297,4,गोविन्द सिंह बस्नेत,पुरुष,51,नेपाल मजदुर किसान पार्टी,गोरखा,2,39.0,NaN,9

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2645,4,विनोद के.सी,पुरुष,33,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),म्याग्दी,1,1,14704,Elected,1
1,2646,4,भिम प्रसाद गौचन,पुरुष,76,राष्ट्रिय प्रजातन्त्र पार्टी,म्याग्दी,1,1,12175,NaN,2

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,NaN,4.0,महेन्द्र बहादुर थकाली,पुरुष,59,नेपाल कम्युनिष्ट पार्टी (एमाले),मुस्तांग,1,2,2584,Elected,1
1,2642.0,4.0,छिरीङ धावा गुरुङ,पुरुष,68,नेपाली काँग्रेस,मुस्तांग,1,2,2259,NaN,2
2,2643.0,4.0,प्रविण कुमार शेरचन,पुरुष,53,राष्ट्रिय प्रजातन्त्र पार्टी (प्रजातान्त्रिक),मुस्तांग,1,2,32,NaN,3
3,2644.0,NaN,नर वहादुर हिराचन,पुरुष,75,राष्ट्रिय प्रजातन्त्र पार्टी,मुस्तांग,1,2,12,NaN,4

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2673,4,विकास लंसाल,पुरुष,48,नेपाल कम्युनिष्ट पार्टी (एमाले),पर्वत,1,2,15434,Elected,1
1,2674,4,राजेन्द्र प्रसाद तिवारी,पुरुष,41,नेपाली काँग्रेस,पर्वत,1,2,13352,NaN,2
2,2675,4,ड‍ोलनाथ भुसाल,पुरुष,40,राष्ट्रिय जनमोर्चा,पर्वत,1,2,274,NaN,3
3,2676,4,लिलाधर आचार्य,पुरुष,45,नेपाल कम्युनिष्ट पार्टी (माले),पर्वत,1,2,252,NaN,4
4,2677,4,टोकेन्द्र राना,पुरुष,42,राष्ट्रिय जनमुक्ति पार्टी,पर्वत,1,2,162,NaN,5
5,2678,4,ओम बहादुर भण्डारी,पुरुष,41,नयाँ शक्ति पार्टी नेपाल,पर्वत,1,2,55,NaN,6
6,2679,4,जित बहादुर सार्की,पुरुष,57,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,पर्वत,1,2,51,NaN,7
7,2680,4,यज्ञ प्रसाद तिवारी,पुरुष,49,स्वतन्त्र,पर्वत,1,2,4,NaN,8

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2319,4,कृष्णचन्द्र नेपाली पोख्रेल,पुरुष,66,नेपाली काँग्रेस,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,1,17683,Elected,1
1,2320,4,सुर्य प्रसाद न्यौपाने,पुरुष,40,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),नवलपरासी (बर्दघाट सुस्ता पूर्व),1,1,17311,NaN,2
2,2321,4,सन्तोष थापा,पुरुष,32,राष्ट्रिय प्रजातन्त्र पार्टी (प्रजातान्त्रिक),नवलपरासी (बर्दघाट सुस्ता पूर्व),1,1,1044,NaN,3
3,2322,4,भिम प्रसाद आचार्य,पुरुष,27,विवेकशील साझा पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,1,827,NaN,4
4,2323,4,चन्द्रदत्त सापकोटा,पुरुष,50,राष्ट्रिय जनमोर्चा,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,1,755,NaN,5
5,2324,4,रुम वहादुर मगर,पुरुष,46,मंगोल नेशनल अर्गनाइजेसन,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,1,534,NaN,6
6,2325,4,शरद मणी खरेल,पुरुष,35,नयाँ शक्ति पार्टी नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,1,397,NaN,7
7,2326,4,टेकदत्तहरि पौडेल,पुरुष,37,राष्ट्रिय प्रजातन्त्र पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,1,245,NaN,8
8,2327,4,धन बहादुर गुरुङ,पुरुष,46,संघीय समाजवादी फोरम नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,1,229,NaN,9
9,2328,4,मन बहादुर लुंगेली,पुरुष,80,राष्ट्रिय जनमुक्ति पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,1,218,NaN,10

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2667,4,नेत्रनाथ अधिकारी,पुरुष,52,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),पर्वत,1,1,21508,Elected,1
1,2668,4,नवराज गुरुङ्ग,पुरुष,61,नेपाली काँग्रेस,पर्वत,1,1,16685,NaN,2
2,2669,4,टिकाराम पुन मगर,पुरुष,29,राष्ट्रिय जनमुक्ति पार्टी,पर्वत,1,1,166,NaN,3
3,2670,4,महेन्द्र जंग लामीछाने,पुरुष,49,नयाँ शक्ति पार्टी नेपाल,पर्वत,1,1,148,NaN,4
4,2671,4,राजेन्द्र प्रसाद शर्मा,पुरुष,45,राष्ट्रिय जनमोर्चा,पर्वत,1,1,119,NaN,5
5,2672,4,महान बहादुर गुरुङग,पुरुष,63,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,पर्वत,1,1,101,NaN,6

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1335,4,जगत बहादुर सुनार (विश्वकर्मा),पुरुष,43.0,नेपाल कम्युनिष्ट पार्टी (एमाले),कास्की,3.0,32690,Elected,1
1,1336,4,शुक्रराज शर्मा,पुरुष,70.0,नेपाली काँग्रेस,कास्की,3.0,24304,NaN,2
2,1337,4,मिलन अधिकारी,पुरुष,25.0,विवेकशील साझा पार्टी,कास्की,3.0,827,NaN,3
3,1338,4,रमेश बसेल,पुरुष,NaN,जनसमाजवादी पार्टी नेपाल,कास्की,3.0,735,NaN,4
4,1339,4,नारायण प्रसाद भण्डारी,पुरुष,39.0,नयाँ शक्ति पार्टी नेपाल,कास्की,3.0,476,NaN,5
5,1340,4,डिल बहादुर नेपाली,पुरुष,43.0,संघीय समाजवादी फोरम नेपाल,कास्की,3.0,347,NaN,6
6,1341,4,हिम लाल गौतम,पुरुष,38.0,राष्ट्रिय जनमोर्चा,कास्की,3.0,154,NaN,7
7,1342,4,गोविन्द बहादुर गजमेर,पुरुष,48.0,मंगोल नेशनल अर्गनाइजेसन,कास्की,3.0,75,NaN,8
8,1343,4,भोज राज त्रिपाठी,पुरुष,45.0,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,कास्की,NaN,50,NaN,9
9,1344,4,दुर्गा बहादुर कामी सुनार,पुरुष,54.0,नेपाल दलित पार्टी,कास्की,3.0,21,NaN,10
10,1345,4,दुर्गा दत्त तिमिल्सिना,NaN,62.0,स्वतन्त्र,कास्की,3.0,17,NaN,11

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2662,4.0,टेक बहादुर घर्ती,पुरुष,46,राष्ट्रिय जनमोर्चा,बागलुङ,2,2,11884,Elected,1
1,2663,4.0,जीत बहादुर शेरचन,पुरुष,38,नेपाली काँग्रेस,बागलुङ,2,2,8624,NaN,2
2,2664,4.0,दिल बहादुर वि‍ क‍,पुरुष,41,आमूल परिवर्तन मसिहा पार्टी नेपाल,बागलुङ,2,2,156,NaN,3
3,2665,4.0,यम कुमार पुन,पुरुष,32,संघीय समाजवादी फोरम नेपाल,बागलुङ,2,2,156,NaN,4
4,2666,4.0,टेक बहादुर कुवँर,पुरुष,49,नयाँ शक्ति पार्टी नेपाल,बागलुङ,2,2,77,NaN,5
5,2666,NaN,टेक बहादुर कुवँर,पुरुष,49,नयाँ शक्ति पार्टी,Nan,2,2,77,NaN,5

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2639,4,इन्द्र धारा डादु विष्ट,पुरुष,48,नेपाल कम्युनिष्ट पार्टी (एमाले),मुस्तांग,1,1,1167,Elected,1.0
1,2640,4,मिक्युर गुरुङ,पुरुष,45,नेपाली काँग्रेस,मुस्तांग,1,1,657,NaN,NaN

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2118,4,पृथ्‍वी सुव्वा गुरुङ,पुरुष,59.0,नेपाल कम्युनिष्ट पार्टी (एमाले),लमजुंग,1,2,23088,Elected,1.0
1,2119,4,कृष्‍ण प्रसाद कोईराला,पुरुष,53.0,नेपाली काँग्रेस,लमजुंग,1,2,15102,NaN,2.0
2,2120,4,उत्तम गुरुङ,पुरुष,47.0,स्वतन्त्र,लमजुंग,1,2,323,NaN,3.0
3,2121,4,हर्के सार्की,पुरुष,64.0,जनसमाजवादी पार्टी नेपाल,लमजुंग,1,2,295,NaN,NaN
4,2122,4,मुनिन्‍द्र थापा,पुरुष,28.0,विवेकशील साझा पार्टी,लमजुंग,1,2,275,NaN,5.0
5,2123,4,सरोज कुमार दनाई,पुरुष,51.0,नयाँ शक्ति पार्टी नेपाल,लमजुंग,1,2,137,NaN,6.0
6,2124,4,नन्द जङ गुरुङ,पुरुष,34.0,आमूल परिवर्तन मसिहा पार्टी नेपाल,लमजुंग,1,2,124,NaN,7.0
7,2125,4,सुरेस कुमार गुरुङ,पुरुष,NaN,संघीय समाजवादी फोरम नेपाल,लमजुंग,1,2,103,NaN,8.0
8,2126,4,बिशाल कार्की,महिला,28.0,NaN,लमजुंग,1,2,103,NaN,9.0

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2230,4,मोहन प्रसाद रेग्मी,पुरुष,58.0,नेपाल कम्युनिष्ट पार्टी (एमाले),स्याङ्जा,2,1,16613,Elected,1.0
1,2231,4,विष्णु पौडेल,पुरुष,33.0,नेपाली काँग्रेस,स्याङ्जा,2,1,13140,NaN,2.0
2,2232,4,राजु गुरुङ्ग,पुरुष,NaN,मंगोल नेशनल अर्गनाइजेसन,स्याङ्जा,2,1,165,NaN,3.0
3,2233,4,रविन पाठक,पुरुष,33.0,नयाँ शक्ति पार्टी नेपाल,स्याङ्जा,2,1,160,NaN,4.0
4,2234,4,कृष्ण माया राना,महिला,49.0,राष्ट्रिय जनमुक्ति पार्टी,स्याङ्जा,2,1,123,NaN,5.0
5,2235,4,मेनुका सार्की,महिला,39.0,राष्ट्रिय जनमोर्चा,स्याङ्जा,2,1,113,NaN,6.0
6,2236,4,भिम बहादुर गोदार,पुरुष,63.0,राष्ट्रिय प्रजातन्त्र पार्टी,स्याङ्जा,2,1,99,NaN,NaN

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2110,4,राजिव गुरुङ,पुरुष,48,स्वतन्त्र,मनाङ्ग,1,2,1410,Elected,1
1,2111,4,कर्म गुरुङ्ग,पुरुष,63,नेपाली काँग्रेस,NaN,1,2,1020,NaN,2

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2656,4,कृष्ण थापा,पुरुष,56,राष्ट्रिय जनमोर्चा,बागलुङ,1,2,15636,Elected,1
1,2657,4,प्रकाश शर्मा पौडेल,पुरुष,59,नेपाली काँग्रेस,बागलुङ,1,2,9094,NaN,2
2,2658,4,युनिस मिया,पुरुष,36,नयाँ शक्ति पार्टी नेपाल,बागलुङ,1,2,310,NaN,3

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1281,4,हरि राज अधिकारी,पुरुष,49.0,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),गोरखा,1,29860,Elected,1
1,1282,4,चिनकाजी श्रेष्ठ,पुरुष,68.0,नेपाली काँग्रेस,गोरखा,1,26643,NaN,2
2,1283,4,नारायण बाबु आचार्य,पुरुष,NaN,नेपाल कम्युनिष्ट पार्टी (माले),गोरखा,1,1639,NaN,3
3,1284,4,दिपेन्द्र गुरुङ,पुरुष,30.0,संघीय समाजवादी फोरम नेपाल,गोरखा,1,539,NaN,4
4,1285,4,अमृत पुडासेनी,पुरुष,33.0,विवेकशील साझा पार्टी,गोरखा,1,256,NaN,5
5,1286,4,कृष्ण गोपाल बन्जारा,पुरुष,52.0,नेपाल संघीय समाजवादी पार्टी,गोरखा,1,156,NaN,6
6,1285,4,अमृत पुडासेनी,पुरुष,33.0,विवेकशील साझा पार्टी,गोरखा,1,256121,NaN,5
7,1287,4,आकाश राना मगर,पुरुष,32.0,मंगोल नेशनल अर्गनाइजेसन,गोरखा,1,110,NaN,7
8,1288,4,राम बहादुर नेपाली,पुरुष,37.0,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,गोरखा,1,81,NaN,8

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1298,4,पोल्देन छोपाङ गुरुङ्ग,पुरुष,58,नेपाल कम्युनिष्ट पार्टी (एमाले),मनाङ्ग,1,2300,Elected,1
1,1299,4,टेक बहादुर गुरुङ,पुरुष,62,नेपाली काँग्रेस,मनाङ्ग,1,2021,NaN,2

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2237.0,4,भगवत प्रकाश मल्ल,पुरुष,41,नेपाली काँग्रेस,स्याङ्जा,2,2,19170,Elected,1.0
1,2238.0,4,सुर्य प्रसाद गैह्रे,पुरुष,31,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),स्याङ्जा,2,2,17630,NaN,NaN
2,2239.0,4,बम बहादुर लामिछाने,पुरुष,44,राष्ट्रिय जनमुक्ति पार्टी,स्याङ्जा,2,2,609,NaN,3.0
3,2240.0,4,रुद्र बहादुर खत्री क्षेत्री,पुरुष,52,राष्ट्रिय प्रजातन्त्र पार्टी,स्याङ्जा,2,2,96,NaN,4.0
4,NaN,4,भरत पाठक,पुरुष,53,नयाँ शक्ति पार्टी नेपाल,स्याङ्जा,2,2,94,NaN,5.0

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1311,4.0,खगराज अधिकारी,पुरुष,55,नेपाल कम्युनिष्ट पार्टी (एमाले),कास्की,1.0,39242,Elected,1
1,1312,4.0,यज्ञ बहादुर थापा,पुरुष,63,नेपाली काँग्रेस,कास्की,1.0,25826,NaN,2
2,1313,4.0,मन बहादुर गुरुङ्ग,पुरुष,60,संघीय समाजवादी फोरम नेपाल,कास्की,1.0,786,NaN,3
3,1314,NaN,दिपक पौडेल,पुरुष,32,विवेकशील साझा पार्टी,कास्की,1.0,589,NaN,4
4,1315,4.0,चन्द्र बहादुर रानाभाट,पुरुष,57,नेपाली कांग्रेस (बी.पी.),कास्की,1.0,346,NaN,5
5,1316,4.0,सौगात पोखरेल,पुरुष,28,नयाँ शक्ति पार्टी नेपाल,कास्की,1.0,234,NaN,6
6,1317,4.0,रियाज गुरुङ्ग,पुरुष,31,मंगोल नेशनल अर्गनाइजेसन,कास्की,NaN,175,NaN,7
7,1318,4.0,टेक बहादुर गुरुङ,पुरुष,50,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,कास्की,1.0,105,NaN,8
8,1319,4.0,मदन मुरारी घिमीरे,पुरुष,54,राष्ट्रिय जनमोर्चा,कास्की,1.0,100,NaN,9
9,1319,4.0,हरी बहादुर खनाल,पुरुष,54,युवा पार्टी,कास्की,1.0,100,NaN,9
10,1320,4.0,पदम बहादुर गुरुङ्ग,पुरुष,64,आमूल परिवर्तन मसिहा पार्टी नेपाल,कास्की,1.0,73,NaN,10
11,1321,4.0,राजु परियार,पुरुष,40,नेपाल दलित पार्टी,कास्की,1.0,10,NaN,11

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2350,4,जनक लाल श्रेक्ष्‍ठ,पुरुष,67,नेपाल कम्युनिष्ट पार्टी (एमाले),नवलपरासी (बर्दघाट सुस्ता पूर्व),2,2,19376,Elected,1
1,2351,4,गणेश मान श्रेष्‍ठ,पुरुष,59,नेपाली काँग्रेस,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,2,19047,NaN,2
2,2352,4,मोहन सिँह थापा वाकवल,पुरुष,40,राष्ट्रिय जनमुक्ति पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,2,533,NaN,3
3,2353,4,लोक बहादुर के.सी खत्री,पुरुष,47,नयाँ शक्ति पार्टी नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,2,119,NaN,4
4,2354,4,टेक प्रसाद पोख्रेल,पुरुष,38,राष्ट्रिय जनमोर्चा,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,2,72,NaN,5
5,2355,4,अर्जुन कुमार भुसाल,पुरुष,44,राष्ट्रिय प्रजातन्त्र पार्टी (प्रजातान्त्रिक),नवलपरासी (बर्दघाट सुस्ता पूर्व),2,2,62,NaN,6
6,2356,4,श्याम बहादुर कुमाल,पुरुष,64,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,2,49,NaN,7
7,2357,4,कृष्‍ण बहादुर दर्जी,पुरुष,67,राष्ट्रिय प्रजातन्त्र पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,2,47,NaN,8
8,2358,4,अञ्जना डल्लाकोटी,महिला,33,राष्ट्रिय शिवसेना पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,2,10,NaN,9
9,2359,4,धर्म वहादुर घर्ति क्षेत्री,पुरुष,63,स्वतन्त्र,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,2,6,NaN,10
10,2360,4,हरी कुमार श्रेष्‍ठ,पुरुष,43,स्वतन्त्र,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,2,1,NaN,11

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2219,4.0,दिपक थापा,पुरुष,47,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),स्याङ्जा,1.0,1.0,17392.0,Elected,1.0
1,2220,NaN,कमल प्रसाद पंगेनी,पुरुष,53,नेपाली काँग्रेस,स्याङ्जा,1.0,1.0,14666.0,NaN,2.0
2,2221,4.0,भूमीजङ् के.सी.,NaN,76,राष्ट्रिय प्रजातन्त्र पार्टी,स्याङ्जा,NaN,1.0,444.0,NaN,3.0
3,2222,4.0,रुद्र बहादुर थापा,पुरुष,69,राष्ट्रिय जनमुक्ति पार्टी,NaN,1.0,1.0,156.0,NaN,4.0
4,2223,4.0,दुर्गा राम गुरुङ,पुरुष,60,मंगोल नेशनल अर्गनाइजेसन,स्याङ्जा,1.0,1.0,133.0,NaN,5.0
5,2224,4.0,राम बहादुर दर्जी,पुरुष,53,wrc दल,1,1.0,NaN,NaN,6,NaN

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1593,4,भुपेन्द्र बहादुर थापा,पुरुष,50,नेपाल कम्युनिष्ट पार्टी (एमाले),म्याग्दी,1,23308,Elected,1
1,1594,4,खम बहादुर गर्बुजा,पुरुष,52,नेपाली काँग्रेस,म्याग्दी,1,20980,NaN,2
2,1595,4,राम बहादुर शाही,पुरुष,59,एकीकृत राष्ट्रिय प्रजातन्त्र पार्टी(राष्ट्रवादी),म्याग्दी,1,309,NaN,3
3,1596,4,नारायण शर्मा,NaN,35,नयाँ शक्ति पार्टी नेपाल,म्याग्दी,1,142,NaN,4
4,1597,4,रन बहादुर फगामी,पुरुष,54,मंगोल नेशनल अर्गनाइजेसन,म्याग्दी,1,113,NaN,5
5,1598,4,फौज बहादुर कार्की,पुरुष,46,राष्ट्रिय जनमोर्चा,म्याग्दी,1,97,NaN,6
6,1599,4,तिलक बहादुर थापा मगर,पुरुष,56,राष्ट्रिय जनमुक्ति पार्टी,म्याग्दी,1,30,NaN,7

        District     Male   Female  Third Gender     Total
0         Achham    60441    67299             2    127742
1   Arghakhanchi    60296    66403             0    126699
2        Baglung    73963    82839             0    156802
3        Baitadi    60227    64596             1    124824
4        Bajhang    47888    49721             1     97610
..           ...      ...      ...           ...       ...
75        Tanahu    90144  3104327             0    194471
76     Taplejung    37187    33591             0     70778
77     Terhathum    30334    30370             0     60704
78      Udayapur    88510    86951             0    175461
79         Total  7069714  6984625           143  14054482

[80 rows x 5 columns]

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1430,4.0,शशांक कोइराला,पुरुष,59,नेपाली काँग्रेस,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,40620.0,Elected,1
1,1431,4.0,भविसोर पराजुली,पुरुष,42,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),नवलपरासी (बर्दघाट सुस्ता पूर्व),1,36596.0,NaN,2
2,1432,4.0,हरि प्रसाद गौतम,पुरुष,35,विवेकशील साझा पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,1082.0,NaN,3
3,1433,NaN,कृष्ण प्रसाद शर्मा गौतम,पुरुष,43,नयाँ शक्ति पार्टी नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,843.0,NaN,4
4,1434,4.0,तिलक थापा मगर,पुरुष,61,राष्ट्रिय जनमुक्ति पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,711.0,NaN,5
5,1435,4.0,कुमार गुरुङ,पुरुष,32,मंगोल नेशनल अर्गनाइजेसन,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,NaN,NaN,6
6,1436,4.0,गोपाल गिरी,पुरुष,61,राष्ट्रिय जनमोर्चा,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,573.0,NaN,7
7,1437,4.0,पिताम्वर तिवारी,पुरुष,52,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),1,165.0,NaN,8

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2339,4,विष्णु प्रसाद लामिछाने,पुरुष,46,नेपाली काँग्रेस,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,1,19222,Elected,1
1,2340,4,वाल कृष्ण गैरे,पुरुष,56,नेपाल कम्युनिष्ट पार्टी (माओवादी केन्द्र),नवलपरासी (बर्दघाट सुस्ता पूर्व),2,1,18161,NaN,2
2,2341,4,विष्‍णु प्रसाद बोटे,पुरुष,26,जनसमाजवादी पार्टी नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,1,886,NaN,3
3,2342,4,भोज बहादुर चौधरी,पुरुष,41,नयाँ शक्ति पार्टी नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,1,397,NaN,4
4,2343,4,गिर बहादुर महतारा,पुरुष,59,राष्ट्रिय जनमोर्चा,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,1,216,NaN,5
5,2344,4,नुन बहादुर आले मगर,पुरुष,44,राष्ट्रिय प्रजातन्त्र पार्टी (प्रजातान्त्रिक),नवलपरासी (बर्दघाट सुस्ता पूर्व),2,1,145,NaN,6
6,2345,4,तिल बहादुर झेंडी मगर,पुरुष,42,राष्ट्रिय जनमुक्ति पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,1,118,NaN,7
7,2346,4,घनश्‍याम अधिकारी,पुरुष,65,राष्ट्रिय प्रजातन्त्र पार्टी,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,1,92,NaN,8
8,2347,4,बुद्धिलाल राना मगर,पुरुष,63,संघीय समाजवादी फोरम नेपाल,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,1,86,NaN,9
9,2348,4,चोला कान्त कंडेल,पुरुष,56,स्वतन्त्र,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,1,6,NaN,10
10,2349,4,देवका गौतम,महिला,36,स्वतन्त्र,नवलपरासी (बर्दघाट सुस्ता पूर्व),2,1,6,NaN,11

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,TotalVotesReceived,EStatus,Rank
0,1357,4,केदार सिग्देल,पुरुष,54,नेपाल कम्युनिष्ट पार्टी (एमाले),तनहुँ,2,32924,Elected,1
1,1358,4,शंकर भण्डारी,पुरुष,490,नेपाली काँग्रेस,तनहुँ,2,29645,NaN,2
2,1359,4,जित बहादुर परियार,पुरुष,56,नेपाल कम्युनिष्ट पार्टी (माले),तनहुँ,2,1168,NaN,3
3,1360,4,पुर्ण बहादुर राना,पुरुष,38,राष्ट्रिय जनमुक्ति पार्टी,तनहुँ,2,800,NaN,4
4,1361,4,कृष्ण राज घिमिरे,पुरुष,59,नयाँ शक्ति पार्टी नेपाल,तनहुँ,2,206,NaN,5
5,1362,4,यम बहादुर आले,पुरुष,62,नेपाली कांग्रेस (बी.पी.),तनहुँ,2,50000,NaN,6
6,1363,4,नर बहादुर थापा,पुरुष,44,राष्ट्रिय जनमोर्चा,तनहुँ,2,114,NaN,7
7,1364,4,शुक बहादुर थापा,पुरुष,36,मंगोल नेशनल अर्गनाइजेसन,तनहुँ,2,93,NaN,8
8,1365,4,विजय कुमार शाही,NaN,51,एकीकृत राष्ट्रिय प्रजातन्त्र पार्टी(राष्ट्रवादी),तनहुँ,2,80,NaN,9
9,1366,4,बाबुराम सुवेदी,पुरुष,57,देशभक्त जनगणतान्त्रिक मोर्चा नेपाल,तनहुँ,2,56,NaN,10

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2647,4,नरदेवी पुन मगर,महिला,48.0,नेपाल कम्युनिष्ट पार्टी (एमाले),म्याग्दी,1,2,10868,NaN,1
1,2648,4,अम लाल फगामी पुन,पुरुष,69.0,नेपाली काँग्रेस,म्याग्दी,1,2,7990,NaN,2
2,2649,4,रमेश कुमार पुन,पुरुष,NaN,राष्ट्रिय जनमोर्चा,म्याग्दी,1,2,57,NaN,3
3,2650,4,छम बहादुर रोका,पुरुष,37.0,राष्ट्रिय जनमुक्ति पार्टी,म्याग्दी,1,2,35,NaN,4

In [146]:

dff =pd.concat([df],ignore_index=True)

In [147]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SerialNo            4 non-null      int64
 1   StateID             4 non-null      int64
 2   CandidateName       4 non-null      object
 3   Gender              4 non-null      object
 4   Age                 3 non-null      float64
 5   PoliticalPartyName  4 non-null      object
 6   DistrictName        4 non-null      object
 7   CenterConstID       4 non-null      int64
 8   SCConstID           4 non-null      int64
 9   TotalVotesReceived  4 non-null      int64
 10  EStatus             0 non-null      float64
 11  Rank                4 non-null      int64
dtypes: float64(2), int64(6), object(4)
memory usage: 512.0+ bytes

In [148]:
dff.head()

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2647,4,नरदेवी पुन मगर,महिला,48.0,नेपाल कम्युनिष्ट पार्टी (एमाले),म्याग्दी,1,2,10868,NaN,1
1,2648,4,अम लाल फगामी पुन,पुरुष,69.0,नेपाली काँग्रेस,म्याग्दी,1,2,7990,NaN,2
2,2649,4,रमेश कुमार पुन,पुरुष,NaN,राष्ट्रिय जनमोर्चा,म्याग्दी,1,2,57,NaN,3
3,2650,4,छम बहादुर रोका,पुरुष,37.0,राष्ट्रिय जनमुक्ति पार्टी,म्याग्दी,1,2,35,NaN,4

In [149]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SerialNo            4 non-null      int64
 1   StateID             4 non-null      int64
 2   CandidateName       4 non-null      object
 3   Gender              4 non-null      object
 4   Age                 3 non-null      float64
 5   PoliticalPartyName  4 non-null      object
 6   DistrictName        4 non-null      object
 7   CenterConstID       4 non-null      int64
 8   SCConstID           4 non-null      int64
 9   TotalVotesReceived  4 non-null      int64
 10  EStatus             0 non-null      float64
 11  Rank                4 non-null      int64
dtypes: float64(2), int64(6), object(4)
memory usage: 512.0+ bytes

In [150]:
dff.head()

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2647,4,नरदेवी पुन मगर,महिला,48.0,नेपाल कम्युनिष्ट पार्टी (एमाले),म्याग्दी,1,2,10868,NaN,1
1,2648,4,अम लाल फगामी पुन,पुरुष,69.0,नेपाली काँग्रेस,म्याग्दी,1,2,7990,NaN,2
2,2649,4,रमेश कुमार पुन,पुरुष,NaN,राष्ट्रिय जनमोर्चा,म्याग्दी,1,2,57,NaN,3
3,2650,4,छम बहादुर रोका,पुरुष,37.0,राष्ट्रिय जनमुक्ति पार्टी,म्याग्दी,1,2,35,NaN,4

In [157]:
dff.tail()

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2647,4,नरदेवी पुन मगर,महिला,48.0,नेपाल कम्युनिष्ट पार्टी (एमाले),म्याग्दी,1,2,10868,NaN,1
1,2648,4,अम लाल फगामी पुन,पुरुष,69.0,नेपाली काँग्रेस,म्याग्दी,1,2,7990,NaN,2
2,2649,4,रमेश कुमार पुन,पुरुष,NaN,राष्ट्रिय जनमोर्चा,म्याग्दी,1,2,57,NaN,3
3,2650,4,छम बहादुर रोका,पुरुष,37.0,राष्ट्रिय जनमुक्ति पार्टी,म्याग्दी,1,2,35,NaN,4

In [151]:
df.head()

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2647,4,नरदेवी पुन मगर,महिला,48.0,नेपाल कम्युनिष्ट पार्टी (एमाले),म्याग्दी,1,2,10868,NaN,1
1,2648,4,अम लाल फगामी पुन,पुरुष,69.0,नेपाली काँग्रेस,म्याग्दी,1,2,7990,NaN,2
2,2649,4,रमेश कुमार पुन,पुरुष,NaN,राष्ट्रिय जनमोर्चा,म्याग्दी,1,2,57,NaN,3
3,2650,4,छम बहादुर रोका,पुरुष,37.0,राष्ट्रिय जनमुक्ति पार्टी,म्याग्दी,1,2,35,NaN,4

In [152]:
df.tail()

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2647,4,नरदेवी पुन मगर,महिला,48.0,नेपाल कम्युनिष्ट पार्टी (एमाले),म्याग्दी,1,2,10868,NaN,1
1,2648,4,अम लाल फगामी पुन,पुरुष,69.0,नेपाली काँग्रेस,म्याग्दी,1,2,7990,NaN,2
2,2649,4,रमेश कुमार पुन,पुरुष,NaN,राष्ट्रिय जनमोर्चा,म्याग्दी,1,2,57,NaN,3
3,2650,4,छम बहादुर रोका,पुरुष,37.0,राष्ट्रिय जनमुक्ति पार्टी,म्याग्दी,1,2,35,NaN,4

In [153]:
df.describe()

,SerialNo,StateID,Age,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
count,4.000000,4.0,3.000000,4.0,4.0,4.000000,0.0,4.000000
mean,2648.500000,4.0,51.333333,1.0,2.0,4737.500000,NaN,2.500000
std,1.290994,0.0,16.258331,0.0,0.0,5543.235307,NaN,1.290994
min,2647.000000,4.0,37.000000,1.0,2.0,35.000000,NaN,1.000000
25%,2647.750000,4.0,42.500000,1.0,2.0,51.500000,NaN,1.750000
50%,2648.500000,4.0,48.000000,1.0,2.0,4023.500000,NaN,2.500000
75%,2649.250000,4.0,58.500000,1.0,2.0,8709.500000,NaN,3.250000
max,2650.000000,4.0,69.000000,1.0,2.0,10868.000000,NaN,4.000000

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SerialNo            4 non-null      int64
 1   StateID             4 non-null      int64
 2   CandidateName       4 non-null      object
 3   Gender              4 non-null      object
 4   Age                 3 non-null      float64
 5   PoliticalPartyName  4 non-null      object
 6   DistrictName        4 non-null      object
 7   CenterConstID       4 non-null      int64
 8   SCConstID           4 non-null      int64
 9   TotalVotesReceived  4 non-null      int64
 10  EStatus             0 non-null      float64
 11  Rank                4 non-null      int64
dtypes: float64(2), int64(6), object(4)
memory usage: 512.0+ bytes

In [155]:
df.replace('???? ,np.nan')

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2647,4,नरदेवी पुन मगर,महिला,48.0,नेपाल कम्युनिष्ट पार्टी (एमाले),म्याग्दी,1,2,10868,NaN,1
1,2648,4,अम लाल फगामी पुन,पुरुष,69.0,नेपाली काँग्रेस,म्याग्दी,1,2,7990,NaN,2
2,2649,4,रमेश कुमार पुन,पुरुष,NaN,राष्ट्रिय जनमोर्चा,म्याग्दी,1,2,57,NaN,3
3,2650,4,छम बहादुर रोका,पुरुष,37.0,राष्ट्रिय जनमुक्ति पार्टी,म्याग्दी,1,2,35,NaN,4

In [159]:
df1=df.drop_duplicates(keep='first')

In [160]:
df1

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2647,4,नरदेवी पुन मगर,महिला,48.0,नेपाल कम्युनिष्ट पार्टी (एमाले),म्याग्दी,1,2,10868,NaN,1
1,2648,4,अम लाल फगामी पुन,पुरुष,69.0,नेपाली काँग्रेस,म्याग्दी,1,2,7990,NaN,2
2,2649,4,रमेश कुमार पुन,पुरुष,NaN,राष्ट्रिय जनमोर्चा,म्याग्दी,1,2,57,NaN,3
3,2650,4,छम बहादुर रोका,पुरुष,37.0,राष्ट्रिय जनमुक्ति पार्टी,म्याग्दी,1,2,35,NaN,4

In [162]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 0 to 3
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SerialNo            4 non-null      int64
 1   StateID             4 non-null      int64
 2   CandidateName       4 non-null      object
 3   Gender              4 non-null      object
 4   Age                 3 non-null      float64
 5   PoliticalPartyName  4 non-null      object
 6   DistrictName        4 non-null      object
 7   CenterConstID       4 non-null      int64
 8   SCConstID           4 non-null      int64
 9   TotalVotesReceived  4 non-null      int64
 10  EStatus             0 non-null      float64
 11  Rank                4 non-null      int64
dtypes: float64(2), int64(6), object(4)
memory usage: 416.0+ bytes

In [163]:
df1.isnull()

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,True,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,True,False

In [164]:
df1.isnull().sum()

SerialNo              0
StateID               0
CandidateName         0
Gender                0
Age                   1
PoliticalPartyName    0
DistrictName          0
CenterConstID         0
SCConstID             0
TotalVotesReceived    0
EStatus               4
Rank                  0
dtype: int64

In [165]:
df1.sort_values(by=['Rank'],ascending=True)

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2647,4,नरदेवी पुन मगर,महिला,48.0,नेपाल कम्युनिष्ट पार्टी (एमाले),म्याग्दी,1,2,10868,NaN,1
1,2648,4,अम लाल फगामी पुन,पुरुष,69.0,नेपाली काँग्रेस,म्याग्दी,1,2,7990,NaN,2
2,2649,4,रमेश कुमार पुन,पुरुष,NaN,राष्ट्रिय जनमोर्चा,म्याग्दी,1,2,57,NaN,3
3,2650,4,छम बहादुर रोका,पुरुष,37.0,राष्ट्रिय जनमुक्ति पार्टी,म्याग्दी,1,2,35,NaN,4

In [166]:
df1

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2647,4,नरदेवी पुन मगर,महिला,48.0,नेपाल कम्युनिष्ट पार्टी (एमाले),म्याग्दी,1,2,10868,NaN,1
1,2648,4,अम लाल फगामी पुन,पुरुष,69.0,नेपाली काँग्रेस,म्याग्दी,1,2,7990,NaN,2
2,2649,4,रमेश कुमार पुन,पुरुष,NaN,राष्ट्रिय जनमोर्चा,म्याग्दी,1,2,57,NaN,3
3,2650,4,छम बहादुर रोका,पुरुष,37.0,राष्ट्रिय जनमुक्ति पार्टी,म्याग्दी,1,2,35,NaN,4

In [167]:
df1.tail()

,SerialNo,StateID,CandidateName,Gender,Age,PoliticalPartyName,DistrictName,CenterConstID,SCConstID,TotalVotesReceived,EStatus,Rank
0,2647,4,नरदेवी पुन मगर,महिला,48.0,नेपाल कम्युनिष्ट पार्टी (एमाले),म्याग्दी,1,2,10868,NaN,1
1,2648,4,अम लाल फगामी पुन,पुरुष,69.0,नेपाली काँग्रेस,म्याग्दी,1,2,7990,NaN,2
2,2649,4,रमेश कुमार पुन,पुरुष,NaN,राष्ट्रिय जनमोर्चा,म्याग्दी,1,2,57,NaN,3
3,2650,4,छम बहादुर रोका,पुरुष,37.0,राष्ट्रिय जनमुक्ति पार्टी,म्याग्दी,1,2,35,NaN,4